#!/usr/bin/env python3
"""
build_vsco2_manifest.py — 由 VSCO2 CE (CC0) GitHub repo 生成弦樂多 articulation
取樣 manifest, 走 jsDelivr CDN 懶載入 (不需轉檔/自架 CDN/憑證)。

VSCO2 檔名各樂器/演奏法不一致 (prefix、velocity 編號 v1/v2 vs v1/v3、RR 後綴
rr/RR/_1/無), 故採「枚舉實際檔案」而非假設樣式: 抓 tree → 解析 note + velocity
→ 依 (note, velocity) 分組取第一個 → 兩個 velocity 極值映射成 soft/loud 兩層。

輸出: src/renderer/data/vsco2Manifest.ts (App 直接 import)。
重跑即更新 (純函式, 無副作用)。
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
import urllib.parse
from collections import defaultdict
from pathlib import Path

REPO = "sgossner/VSCO-2-CE"
REF = "master"
JSDELIVR = f"https://cdn.jsdelivr.net/gh/{REPO}@{REF}/"

# 樂器 → (section 資料夾, {本地 articulation key: VSCO2 子資料夾名})
INSTRUMENTS: dict[str, tuple[str, dict[str, str]]] = {
    "violin": (
        "Strings/Violin Section",
        {"sustain": "susVib", "pizz": "Pizz", "staccato": "Spic"},
    ),
    "cello": (
        "Strings/Cello Section",
        {"sustain": "susvib", "pizz": "pizzT", "staccato": "spic"},
    ),
}

NOTE_RE = re.compile(r"_([A-G][#b]?)(\d)_")
VEL_RE = re.compile(r"_v(\d)")


def fetch_tree() -> list[str]:
    # 用 curl 抓 (本機 Python SSL 憑證鏈不全; curl 可靠)。
    url = f"https://api.github.com/repos/{REPO}/git/trees/{REF}?recursive=1"
    out = subprocess.run(
        ["curl", "-sSL", "-H", "User-Agent: score-arranger", url],
        capture_output=True, text=True, timeout=90, check=True,
    ).stdout
    data = json.loads(out)
    return [n["path"] for n in data.get("tree", []) if n["path"].endswith(".wav")]


def build() -> dict:
    paths = fetch_tree()
    manifest: dict[str, dict[str, dict[str, dict[str, str]]]] = {}

    for inst, (section, artics) in INSTRUMENTS.items():
        manifest[inst] = {}
        for artic_key, folder in artics.items():
            prefix = f"{section}/{folder}/"
            files = [p for p in paths if p.startswith(prefix)]
            # (note → {velocity_int → path}); 同組取第一個 (穩定排序後)
            by_note: dict[str, dict[int, str]] = defaultdict(dict)
            vels_seen: set[int] = set()
            for p in sorted(files):
                name = p[len(prefix):]
                nm = NOTE_RE.search(name)
                vm = VEL_RE.search(name)
                if not nm or not vm:
                    continue
                note = f"{nm.group(1)}{nm.group(2)}"
                vel = int(vm.group(1))
                vels_seen.add(vel)
                by_note[note].setdefault(vel, p)
            if not by_note:
                print(f"  ! {inst}/{artic_key}: 無檔案 (folder={folder})",
                      file=sys.stderr)
                continue
            # 兩個 velocity 極值 → soft / loud
            vels = sorted(vels_seen)
            soft_v, loud_v = vels[0], vels[-1]
            layers: dict[str, dict[str, str]] = {"soft": {}, "loud": {}}
            for note, vmap in by_note.items():
                if soft_v in vmap:
                    layers["soft"][note] = JSDELIVR + urllib.parse.quote(vmap[soft_v])
                # loud 缺就用 soft 補 (單層樂器也能播)
                loud_path = vmap.get(loud_v, vmap.get(soft_v))
                if loud_path:
                    layers["loud"][note] = JSDELIVR + urllib.parse.quote(loud_path)
            manifest[inst][artic_key] = layers
            print(f"  {inst}/{artic_key}: {len(layers['soft'])} notes "
                  f"(v{soft_v}/v{loud_v})", file=sys.stderr)
    return manifest


def main() -> None:
    print("Fetching VSCO2 tree + building manifest…", file=sys.stderr)
    manifest = build()
    out = Path(__file__).resolve().parents[2] / "src/renderer/data/vsco2Manifest.ts"
    body = json.dumps(manifest, indent=2, ensure_ascii=False)
    ts = (
        "// AUTO-GENERATED by engine/scripts/build_vsco2_manifest.py — do not edit.\n"
        "// VSCO2 Community Edition (CC0) 弦樂多 articulation 取樣, jsDelivr CDN 懶載入。\n"
        "// instrument → articulation(sustain/pizz/staccato) → layer(soft/loud) → {note: url}\n\n"
        "export type VscoLayer = Record<string, string>;\n"
        "export interface VscoArtic { soft: VscoLayer; loud: VscoLayer }\n"
        "export type VscoManifest = Record<string, Record<string, VscoArtic>>;\n\n"
        f"export const VSCO2_MANIFEST: VscoManifest = {body};\n"
    )
    out.write_text(ts, encoding="utf-8")
    print(f"Wrote {out}", file=sys.stderr)


if __name__ == "__main__":
    main()
