#!/usr/bin/env python3
"""由 core/rpc_schema.CONTRACTS 生成前端 TS 型別 (schema-first RPC 鷹架)。

用法:
  .venv/bin/python3 scripts/gen_rpc_types.py          # 寫檔
  .venv/bin/python3 scripts/gen_rpc_types.py --check  # 只驗不過時 (給 test / CI)

產出: src/renderer/generated/rpc-types.ts
"""
from __future__ import annotations

import sys
import typing
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from core import rpc_schema  # noqa: E402

OUT = (
    Path(__file__).parent.parent.parent
    / "src" / "renderer" / "generated" / "rpc-types.ts"
)


def ts_type(pyt: object) -> str:
    origin = typing.get_origin(pyt)
    if pyt is bool:
        return "boolean"
    if pyt in (int, float):
        return "number"
    if pyt is str:
        return "string"
    if origin in (list, tuple):
        args = typing.get_args(pyt)
        if not args:
            return "unknown[]"
        inner = ts_type(args[0])
        # union 元素要加括號, 否則 `number | null[]` 會被讀成 number | (null[])
        return f"({inner})[]" if "|" in inner else f"{inner}[]"
    if origin is dict:
        return "Record<string, unknown>"
    if origin is typing.Union:
        args = typing.get_args(pyt)
        non_none = [a for a in args if a is not type(None)]
        body = " | ".join(ts_type(a) for a in non_none) or "unknown"
        return f"{body} | null" if len(non_none) < len(args) else body
    if isinstance(pyt, type) and issubclass_typeddict(pyt):
        return pyt.__name__
    return "unknown"


def issubclass_typeddict(t: type) -> bool:
    # TypedDict 類別有 __annotations__ + __total__
    return hasattr(t, "__annotations__") and hasattr(t, "__total__")


def emit_iface(name: str, td: type) -> str:
    hints = typing.get_type_hints(td)
    if not hints:
        # 空契約 → type alias (避免 biome noEmptyInterface; total=False 本就允許任意 key)
        return f"export type {name} = Record<string, unknown>;"
    # 用 __required_keys__ 判每欄選用性 → 支援 total + 逐欄 Required/NotRequired 混用
    required = getattr(td, "__required_keys__", frozenset(hints))
    lines = [f"export interface {name} {{"]
    for key, val in hints.items():
        opt = "" if key in required else "?"
        lines.append(f"  {key}{opt}: {ts_type(val)};")
    lines.append("}")
    return "\n".join(lines)


def collect_typeddicts(pyt: object, acc: dict) -> None:
    """遞迴收集 pyt 內參照到的所有 TypedDict (含巢狀 / list 內)。"""
    if isinstance(pyt, type) and issubclass_typeddict(pyt):
        if pyt.__name__ not in acc:
            acc[pyt.__name__] = pyt
            for val in typing.get_type_hints(pyt).values():
                collect_typeddicts(val, acc)
        return
    for arg in typing.get_args(pyt):
        collect_typeddicts(arg, acc)


def generate() -> str:
    out: list[str] = [
        "// AUTO-GENERATED by engine/scripts/gen_rpc_types.py — 請勿手改。",
        "// 契約來源: engine/core/rpc_schema.py。改契約後重跑 codegen。",
        "",
    ]
    # 收集所有 TypedDict (req/res + 巢狀), 保持插入順序; TS interface 會 hoist 故順序無所謂
    acc: dict[str, type] = {}
    for _method, (req, res) in rpc_schema.CONTRACTS.items():
        collect_typeddicts(req, acc)
        collect_typeddicts(res, acc)
    for name, td in acc.items():
        out.append(emit_iface(name, td))
        out.append("")
    out.append("export interface RpcContracts {")
    for method, (req, res) in rpc_schema.CONTRACTS.items():
        out.append(f"  {method}: {{ req: {req.__name__}; res: {res.__name__} }};")
    out.append("}")
    out.append("")
    out.append("export type RpcMethod = keyof RpcContracts;")
    out.append("")
    return "\n".join(out)


def main() -> int:
    content = generate()
    if "--check" in sys.argv:
        cur = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if cur != content:
            print(
                "✗ rpc-types.ts 過時 — 改了 rpc_schema 請重跑 gen_rpc_types.py",
                file=sys.stderr,
            )
            return 1
        print("✓ rpc-types.ts 是最新的")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    print(f"已生成 {OUT.name} ({len(rpc_schema.CONTRACTS)} methods)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
