// AUTO-GENERATED by scripts/vsco-pipeline/build.mjs — do not edit.
// VSCO2 Community Edition (CC0) 弦樂多 articulation 取樣, jsDelivr CDN 懶載入。
// instrument → articulation(sustain/pizz/staccato/tremolo) → layer(soft/loud)
// → { gainDb, urls }。
//   - gainDb: 逐音符量測 loudest-1s RMS 後, 將該層 median 對齊 -20 dBFS 的
//     增益 — 播放端必須套用 (sampler.volume = gainDb + 樂器 trim), 否則重蹈
//     0.1.110-113 的平衡回歸 (VSCO 各樂器/各層錄音電平差可達 10dB+)。
//   - 音名已 +1 八度校正為 concert pitch (VSCO 弦樂組標籤比實音低一個八度)。

export interface VscoLayer { gainDb: number; urls: Record<string, string> }
export interface VscoArtic { soft: VscoLayer; loud: VscoLayer }
export type VscoManifest = Record<string, Record<string, VscoArtic>>;

export const VSCO2_MANIFEST: VscoManifest = {
  "violin": {
    "sustain": {
      "soft": {
        "gainDb": 16.2,
        "urls": {
          "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_A2_v1.wav",
          "A4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_A3_v1.wav",
          "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_B2_v1.wav",
          "B5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_B4_v1.wav",
          "C5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_C4_v1.wav",
          "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_D3_v1.wav",
          "D6": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_D5_v1.wav",
          "E5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_E4_v1.wav",
          "F#4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_F%233_v1.wav",
          "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_G2_v1.wav",
          "G5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_G4_v1.wav"
        }
      },
      "loud": {
        "gainDb": 10.3,
        "urls": {
          "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_A2_v2.wav",
          "A4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_A3_v2.wav",
          "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_B2_v2.wav",
          "B5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_B4_v2.wav",
          "C5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_C4_v2.wav",
          "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_D3_v2.wav",
          "D6": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_D5_v2.wav",
          "E5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_E4_v2.wav",
          "F#4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_F%233_v2.wav",
          "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_G2_v2.wav",
          "G5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_G4_v2.wav"
        }
      }
    },
    "pizz": {
      "soft": {
        "gainDb": 26.9,
        "urls": {
          "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_A2_v1_rr1.wav",
          "A4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_A3_v1_rr1.wav",
          "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_B2_v1_rr1.wav",
          "B5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_B4_v1_rr1.wav",
          "C5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_C4_v1_rr1.wav",
          "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_D3_v1_rr1.wav",
          "D6": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_D5_v1_rr1.wav",
          "E5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_E4_v1_rr1.wav",
          "F#4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_F%233_v1_rr1.wav",
          "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_G2_v1_rr1.wav",
          "G5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_G4_v1_rr1.wav"
        }
      },
      "loud": {
        "gainDb": 14.2,
        "urls": {
          "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_A2_v2_rr1.wav",
          "A4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_A3_v2_rr1.wav",
          "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_B2_v2_rr1.wav",
          "B5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_B4_v2_rr1.wav",
          "C5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_C4_v2_rr1.wav",
          "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_D3_v2_rr1.wav",
          "D6": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_D5_v2_rr1.wav",
          "E5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_E4_v2_rr1.wav",
          "F#4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_F%233_v2_rr1.wav",
          "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_G2_v2_rr1.wav",
          "G5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_G4_v2_rr1.wav"
        }
      }
    },
    "staccato": {
      "soft": {
        "gainDb": 19.5,
        "urls": {
          "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_A2_v1_rr1.wav",
          "A4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_A3_v1_rr1.wav",
          "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_B2_v1_rr1.wav",
          "B5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_B4_v1_rr1.wav",
          "C5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_C4_v1_rr1.wav",
          "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_D3_v1_rr1.wav",
          "D6": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_D5_v1_rr1.wav",
          "E5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_E4_v1_rr1.wav",
          "F#4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_F%233_v1_rr1.wav",
          "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_G2_v1_rr1.wav",
          "G5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_G4_v1_rr1.wav"
        }
      },
      "loud": {
        "gainDb": 11.5,
        "urls": {
          "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_A2_v2_rr1.wav",
          "A4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_A3_v2_rr1.wav",
          "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_B2_v2_rr1.wav",
          "B5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_B4_v2_rr1.wav",
          "C5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_C4_v2_rr1.wav",
          "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_D3_v2_rr1.wav",
          "D6": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_D5_v2_rr1.wav",
          "E5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_E4_v2_rr1.wav",
          "F#4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_F%233_v2_rr1.wav",
          "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_G2_v2_rr1.wav",
          "G5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_G4_v2_rr1.wav"
        }
      }
    },
    "tremolo": {
      "soft": {
        "gainDb": 20.6,
        "urls": {
          "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_A2_v1.wav",
          "A4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_A3_v1.wav",
          "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_B2_v1.wav",
          "B5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_B4_v1.wav",
          "C5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_C4_v1.wav",
          "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_D3_v1.wav",
          "D6": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_D5_v1.wav",
          "E5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_E4_v1.wav",
          "F#4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_F%233_v1.wav",
          "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_G2_v1.wav",
          "G5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_G4_v1.wav"
        }
      },
      "loud": {
        "gainDb": 3.8,
        "urls": {
          "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_A2_v2.wav",
          "A4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_A3_v2.wav",
          "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_B2_v2.wav",
          "B5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_B4_v2.wav",
          "C5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_C4_v2.wav",
          "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_D3_v2.wav",
          "D6": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_D5_v2.wav",
          "E5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_E4_v2.wav",
          "F#4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_F%233_v1.wav",
          "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_G2_v2.wav",
          "G5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Trem/VlnEns_Trem_G4_v2.wav"
        }
      }
    }
  },
  "viola": {
    "sustain": {
      "soft": {
        "gainDb": 16.4,
        "urls": {
          "A4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_A3_v1_1.wav",
          "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_B2_v1_1.wav",
          "B5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_B4_v1_1.wav",
          "C3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_C2_v1_1.wav",
          "C5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_C4_v1_1.wav",
          "D3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_D2_v1_1.wav",
          "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_D3_v1_1.wav",
          "D6": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_D5_v1_1.wav",
          "E3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_E2_v1_1.wav",
          "E5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_E4_v1_1.wav",
          "F4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_F3_v1_1.wav",
          "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_G2_v1_1.wav",
          "G5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_G4_v1_1.wav"
        }
      },
      "loud": {
        "gainDb": 1.3,
        "urls": {
          "A4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_A3_v2_1.wav",
          "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_B2_v2_1.wav",
          "B5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_B4_v2_1.wav",
          "C3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_C2_v2_1.wav",
          "C5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_C4_v2_1.wav",
          "D3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_D2_v2_1.wav",
          "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_D3_v2_1.wav",
          "D6": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_D5_v2_1.wav",
          "E3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_E2_v2_1.wav",
          "E5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_E4_v2_1.wav",
          "F4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_F3_v2_1.wav",
          "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_G2_v2_1.wav",
          "G5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/susvib/ViolaEns_susvib_G4_v2_1.wav"
        }
      }
    },
    "pizz": {
      "soft": {
        "gainDb": 21,
        "urls": {
          "A4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_A3_v1_rr1.wav",
          "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_B2_v1_rr1.wav",
          "B5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_B4_v1_rr1.wav",
          "C3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_C2_v1_rr1.wav",
          "C5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_C4_v1_rr1.wav",
          "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_D3_v1_rr1.wav",
          "D6": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_D5_v1_rr1.wav",
          "E3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_E2_v1_rr1.wav",
          "E5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_E4_v1_rr1.wav",
          "F4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_F3_v1_rr1.wav",
          "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_G2_v1_rr1.wav",
          "G5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_G4_v1_rr1.wav"
        }
      },
      "loud": {
        "gainDb": 10.1,
        "urls": {
          "A4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_A3_v2_rr1.wav",
          "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_B2_v2_rr1.wav",
          "B5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_B4_v2_rr1.wav",
          "C3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_C2_v2_rr1.wav",
          "C5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_C4_v2_rr1.wav",
          "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_D3_v2_rr1.wav",
          "D6": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_D5_v1_rr1.wav",
          "E3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_E2_v2_rr1.wav",
          "E5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_E4_v2_rr1.wav",
          "F4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_F3_v2_rr1.wav",
          "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_G2_v2_rr1.wav",
          "G5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/pizz/ViolaEns_pizz_G4_v2_rr1.wav"
        }
      }
    },
    "staccato": {
      "soft": {
        "gainDb": 24.5,
        "urls": {
          "A4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_A3_v1_rr1.wav",
          "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_B2_v1_rr1.wav",
          "B5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_B4_v1_rr1.wav",
          "C3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_C2_v1_rr1.wav",
          "C5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_C4_v1_rr1.wav",
          "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_D3_v1_rr1.wav",
          "D6": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_D5_v1_rr1.wav",
          "E3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_E2_v1_rr1.wav",
          "E5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_E4_v1_rr1.wav",
          "F4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_F3_v1_rr1.wav",
          "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_G2_v1_rr1.wav",
          "G5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_G4_v1_rr1.wav"
        }
      },
      "loud": {
        "gainDb": 9.5,
        "urls": {
          "A4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_A3_v2_rr1.wav",
          "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_B2_v2_rr1.wav",
          "B5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_B4_v2_rr1.wav",
          "C3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_C2_v2_rr1.wav",
          "C5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_C4_v2_rr1.wav",
          "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_D3_v2_rr1.wav",
          "D6": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_D5_v2_rr1.wav",
          "E3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_E2_v2_rr1.wav",
          "E5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_E4_v2_rr1.wav",
          "F4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_F3_v2_rr1.wav",
          "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_G2_v2_rr1.wav",
          "G5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/spic/Violas_spic_G4_v2_rr1.wav"
        }
      }
    },
    "tremolo": {
      "soft": {
        "gainDb": 25.6,
        "urls": {
          "A4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_A3_v1_rr1.wav",
          "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_B2_v1_rr1.wav",
          "B5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_B4_v1_rr1.wav",
          "C3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_C2_v1_rr1.wav",
          "C5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_C4_v1_rr1.wav",
          "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_D3_v1_rr1.wav",
          "D6": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_D5_v1_rr1.wav",
          "E3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_E2_v1_rr1.wav",
          "E5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_E4_v1_rr1.wav",
          "F4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_F3_v1_rr1.wav",
          "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_G2_v1_rr1.wav",
          "G5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_G4_v1_rr1.wav"
        }
      },
      "loud": {
        "gainDb": 0.2,
        "urls": {
          "A4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_A3_v2_rr1.wav",
          "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_B2_v2_rr1.wav",
          "B5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_B4_v2_rr1.wav",
          "C3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_C2_v2_rr1.wav",
          "C5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_C4_v2_rr1.wav",
          "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_D3_v2_rr1.wav",
          "D6": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_D5_v2_rr1.wav",
          "E3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_E2_v2_rr1.wav",
          "E5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_E4_v2_rr1.wav",
          "F4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_F3_v2_rr1.wav",
          "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_G2_v2_rr1.wav",
          "G5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Viola%20Section/trem/Violas_trem_G4_v2_rr1.wav"
        }
      }
    }
  },
  "cello": {
    "sustain": {
      "soft": {
        "gainDb": 13.3,
        "urls": {
          "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_A2_v1_1.wav",
          "B2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_B1_v1_1.wav",
          "B4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_B3_v1_1.wav",
          "C2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_C1_v1_1.wav",
          "C4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_C3_v1_1.wav",
          "D3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_D2_v1_1.wav",
          "D5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_D4_v1_1.wav",
          "E2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_E1_v1_1.wav",
          "E4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_E3_v1_1.wav",
          "F3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_F2_v1_1.wav",
          "F5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_F4_v1_1.wav",
          "G2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_G1_v1_1.wav",
          "G4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_G3_v1_1.wav"
        }
      },
      "loud": {
        "gainDb": -1.2,
        "urls": {
          "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_A2_v3_1.wav",
          "B2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_B1_v3_1.wav",
          "B4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_B3_v3_1.wav",
          "C2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_C1_v3_1.wav",
          "C4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_C3_v3_1.wav",
          "D3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_D2_v3_1.wav",
          "D5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_D4_v3_1.wav",
          "E2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_E1_v3_1.wav",
          "E4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_E3_v3_1.wav",
          "F3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_F2_v3_1.wav",
          "F5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_F4_v3_1.wav",
          "G2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_G1_v3_1.wav",
          "G4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_G3_v3_1.wav"
        }
      }
    },
    "pizz": {
      "soft": {
        "gainDb": 19.9,
        "urls": {
          "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_A2_v1_RR1.wav",
          "B2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_B1_v1_RR1.wav",
          "B4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_B3_v1_RR1.wav",
          "C2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_C1_v1_RR1.wav",
          "C4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_C3_v1_RR1.wav",
          "D3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_D2_v1_RR1.wav",
          "D5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_D4_v1_RR1.wav",
          "E2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_E1_v1_RR1.wav",
          "E4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_E3_v1_RR1.wav",
          "F3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_F2_v1_RR1.wav",
          "F5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_F4_v1_RR1.wav",
          "G2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_G1_v1_RR1.wav",
          "G4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_G3_v1_RR1.wav"
        }
      },
      "loud": {
        "gainDb": 10,
        "urls": {
          "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_A2_v2_RR1.wav",
          "B2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_B1_v2_RR1.wav",
          "B4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_B3_v2_RR1.wav",
          "C2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_C1_v2_RR1.wav",
          "C4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_C3_v2_RR1.wav",
          "D3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_D2_v2_RR1.wav",
          "D5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_D4_v2_RR1.wav",
          "E2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_E1_v2_RR1.wav",
          "E4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_E3_v2_RR1.wav",
          "F3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_F2_v2_RR1.wav",
          "F5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_F4_v2_RR1.wav",
          "G2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_G1_v2_RR1.wav",
          "G4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_G3_v2_RR1.wav"
        }
      }
    },
    "staccato": {
      "soft": {
        "gainDb": 21.4,
        "urls": {
          "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_A2_v1_RR1.wav",
          "B2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_B1_v1_RR1.wav",
          "B4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_B3_v1_RR1.wav",
          "C2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_C1_v1_RR1.wav",
          "C4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_C3_v1_RR1.wav",
          "D3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_D2_v1_RR1.wav",
          "D5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_D4_v1_RR1.wav",
          "E2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_E1_v1_RR1.wav",
          "E4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_E3_v1_RR1.wav",
          "F3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_F2_v1_RR1.wav",
          "F5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_F4_v1_RR1.wav",
          "G2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_G1_v1_RR1.wav",
          "G4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_G3_v1_RR1.wav"
        }
      },
      "loud": {
        "gainDb": 9,
        "urls": {
          "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_A2_v2_RR1.wav",
          "B2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_B1_v2_RR1.wav",
          "B4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_B3_v2_RR1.wav",
          "C2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_C1_v2_RR1.wav",
          "C4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_C3_v2_RR1.wav",
          "D3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_D2_v2_RR1.wav",
          "D5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_D4_v2_RR1.wav",
          "E2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_E1_v2_RR1.wav",
          "E4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_E3_v2_RR1.wav",
          "F3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_F2_v2_RR1.wav",
          "F5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_F4_v2_RR1.wav",
          "G2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_G1_v2_RR1.wav",
          "G4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_G3_v2_RR1.wav"
        }
      }
    },
    "tremolo": {
      "soft": {
        "gainDb": 29.6,
        "urls": {
          "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_A2_v1_1.wav",
          "B2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_B1_v1_1.wav",
          "B4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_B3_v1_1.wav",
          "C4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_C3_v1_1.wav",
          "D3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_D2_v1_1.wav",
          "D5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_D4_v1_1.wav",
          "E2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_E1_v1_1.wav",
          "E4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_E3_v1_1.wav",
          "F3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_F2_v1_1.wav",
          "F5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_F4_v1_1.wav",
          "G2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_G1_v1_1.wav",
          "G4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_G3_v1_1.wav"
        }
      },
      "loud": {
        "gainDb": -1.1,
        "urls": {
          "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_A2_v2_1.wav",
          "B2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_B1_v1_1.wav",
          "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_B2_v2_1.wav",
          "B4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_B3_v2_1.wav",
          "C2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_C1_v2_1.wav",
          "C4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_C3_v2_1.wav",
          "D3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_D2_v2_1.wav",
          "D5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_D4_v2_1.wav",
          "E2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_E1_v2_1.wav",
          "E4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_E3_v2_1.wav",
          "F3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_F2_v2_1.wav",
          "F5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_F4_v2_1.wav",
          "G2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_G1_v2_1.wav",
          "G4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/trem/trem_G3_v2_1.wav"
        }
      }
    }
  }
};
