// AUTO-GENERATED by engine/scripts/build_vsco2_manifest.py — do not edit.
// VSCO2 Community Edition (CC0) 弦樂多 articulation 取樣, jsDelivr CDN 懶載入。
// instrument → articulation(sustain/pizz/staccato) → layer(soft/loud) → {note: url}

export type VscoLayer = Record<string, string>;
export interface VscoArtic { soft: VscoLayer; loud: VscoLayer }
export type VscoManifest = Record<string, Record<string, VscoArtic>>;

export const VSCO2_MANIFEST: VscoManifest = {
  "violin": {
    "sustain": {
      "soft": {
        "A2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_A2_v1.wav",
        "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_A3_v1.wav",
        "B2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_B2_v1.wav",
        "B4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_B4_v1.wav",
        "C4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_C4_v1.wav",
        "D3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_D3_v1.wav",
        "D5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_D5_v1.wav",
        "E4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_E4_v1.wav",
        "F#3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_F%233_v1.wav",
        "G2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_G2_v1.wav",
        "G4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_G4_v1.wav"
      },
      "loud": {
        "A2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_A2_v2.wav",
        "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_A3_v2.wav",
        "B2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_B2_v2.wav",
        "B4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_B4_v2.wav",
        "C4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_C4_v2.wav",
        "D3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_D3_v2.wav",
        "D5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_D5_v2.wav",
        "E4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_E4_v2.wav",
        "F#3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_F%233_v2.wav",
        "G2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_G2_v2.wav",
        "G4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/susVib/VlnEns_susVib_G4_v2.wav"
      }
    },
    "pizz": {
      "soft": {
        "A2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_A2_v1_rr1.wav",
        "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_A3_v1_rr1.wav",
        "B2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_B2_v1_rr1.wav",
        "B4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_B4_v1_rr1.wav",
        "C4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_C4_v1_rr1.wav",
        "D3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_D3_v1_rr1.wav",
        "D5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_D5_v1_rr1.wav",
        "E4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_E4_v1_rr1.wav",
        "F#3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_F%233_v1_rr1.wav",
        "G2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_G2_v1_rr1.wav",
        "G4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_G4_v1_rr1.wav"
      },
      "loud": {
        "A2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_A2_v2_rr1.wav",
        "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_A3_v2_rr1.wav",
        "B2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_B2_v2_rr1.wav",
        "B4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_B4_v2_rr1.wav",
        "C4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_C4_v2_rr1.wav",
        "D3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_D3_v2_rr1.wav",
        "D5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_D5_v2_rr1.wav",
        "E4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_E4_v2_rr1.wav",
        "F#3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_F%233_v2_rr1.wav",
        "G2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_G2_v2_rr1.wav",
        "G4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Pizz/VlnEns_Pizz_G4_v2_rr1.wav"
      }
    },
    "staccato": {
      "soft": {
        "A2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_A2_v1_rr1.wav",
        "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_A3_v1_rr1.wav",
        "B2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_B2_v1_rr1.wav",
        "B4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_B4_v1_rr1.wav",
        "C4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_C4_v1_rr1.wav",
        "D3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_D3_v1_rr1.wav",
        "D5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_D5_v1_rr1.wav",
        "E4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_E4_v1_rr1.wav",
        "F#3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_F%233_v1_rr1.wav",
        "G2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_G2_v1_rr1.wav",
        "G4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_G4_v1_rr1.wav"
      },
      "loud": {
        "A2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_A2_v2_rr1.wav",
        "A3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_A3_v2_rr1.wav",
        "B2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_B2_v2_rr1.wav",
        "B4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_B4_v2_rr1.wav",
        "C4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_C4_v2_rr1.wav",
        "D3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_D3_v2_rr1.wav",
        "D5": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_D5_v2_rr1.wav",
        "E4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_E4_v2_rr1.wav",
        "F#3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_F%233_v2_rr1.wav",
        "G2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_G2_v2_rr1.wav",
        "G4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Violin%20Section/Spic/VlnEns_Spic_G4_v2_rr1.wav"
      }
    }
  },
  "cello": {
    "sustain": {
      "soft": {
        "A2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_A2_v1_1.wav",
        "B1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_B1_v1_1.wav",
        "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_B3_v1_1.wav",
        "C1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_C1_v1_1.wav",
        "C3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_C3_v1_1.wav",
        "D2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_D2_v1_1.wav",
        "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_D4_v1_1.wav",
        "E1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_E1_v1_1.wav",
        "E3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_E3_v1_1.wav",
        "F2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_F2_v1_1.wav",
        "F4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_F4_v1_1.wav",
        "G1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_G1_v1_1.wav",
        "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_G3_v1_1.wav"
      },
      "loud": {
        "A2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_A2_v3_1.wav",
        "B1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_B1_v3_1.wav",
        "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_B3_v3_1.wav",
        "C1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_C1_v3_1.wav",
        "C3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_C3_v3_1.wav",
        "D2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_D2_v3_1.wav",
        "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_D4_v3_1.wav",
        "E1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_E1_v3_1.wav",
        "E3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_E3_v3_1.wav",
        "F2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_F2_v3_1.wav",
        "F4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_F4_v3_1.wav",
        "G1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_G1_v3_1.wav",
        "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/susvib/susvib_G3_v3_1.wav"
      }
    },
    "pizz": {
      "soft": {
        "A2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_A2_v1_RR1.wav",
        "B1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_B1_v1_RR1.wav",
        "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_B3_v1_RR1.wav",
        "C1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_C1_v1_RR1.wav",
        "C3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_C3_v1_RR1.wav",
        "D2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_D2_v1_RR1.wav",
        "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_D4_v1_RR1.wav",
        "E1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_E1_v1_RR1.wav",
        "E3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_E3_v1_RR1.wav",
        "F2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_F2_v1_RR1.wav",
        "F4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_F4_v1_RR1.wav",
        "G1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_G1_v1_RR1.wav",
        "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_G3_v1_RR1.wav"
      },
      "loud": {
        "A2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_A2_v2_RR1.wav",
        "B1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_B1_v2_RR1.wav",
        "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_B3_v2_RR1.wav",
        "C1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_C1_v2_RR1.wav",
        "C3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_C3_v2_RR1.wav",
        "D2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_D2_v2_RR1.wav",
        "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_D4_v2_RR1.wav",
        "E1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_E1_v2_RR1.wav",
        "E3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_E3_v2_RR1.wav",
        "F2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_F2_v2_RR1.wav",
        "F4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_F4_v2_RR1.wav",
        "G1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_G1_v2_RR1.wav",
        "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/pizzT/pizzT_G3_v2_RR1.wav"
      }
    },
    "staccato": {
      "soft": {
        "A2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_A2_v1_RR1.wav",
        "B1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_B1_v1_RR1.wav",
        "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_B3_v1_RR1.wav",
        "C1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_C1_v1_RR1.wav",
        "C3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_C3_v1_RR1.wav",
        "D2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_D2_v1_RR1.wav",
        "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_D4_v1_RR1.wav",
        "E1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_E1_v1_RR1.wav",
        "E3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_E3_v1_RR1.wav",
        "F2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_F2_v1_RR1.wav",
        "F4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_F4_v1_RR1.wav",
        "G1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_G1_v1_RR1.wav",
        "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_G3_v1_RR1.wav"
      },
      "loud": {
        "A2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_A2_v2_RR1.wav",
        "B1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_B1_v2_RR1.wav",
        "B3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_B3_v2_RR1.wav",
        "C1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_C1_v2_RR1.wav",
        "C3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_C3_v2_RR1.wav",
        "D2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_D2_v2_RR1.wav",
        "D4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_D4_v2_RR1.wav",
        "E1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_E1_v2_RR1.wav",
        "E3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_E3_v2_RR1.wav",
        "F2": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_F2_v2_RR1.wav",
        "F4": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_F4_v2_RR1.wav",
        "G1": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_G1_v2_RR1.wav",
        "G3": "https://cdn.jsdelivr.net/gh/sgossner/VSCO-2-CE@master/Strings/Cello%20Section/spic/spic_G3_v2_RR1.wav"
      }
    }
  }
};
